---
site_name: YVtils Documentation
site_url: 'https://docs.yvtils.net/'

theme: 
  logo: assets/logo_transparent.webp
  favicon: assets/logo_transparent.webp
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/YVtils'
    - icon: fontawesome/brands/discord
      link: 'https://yvtils.net/yvtils/support'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/@WolfiiYV'

copyright: Copyright &copy; 2024 YVtils

plugins:
  - mkdocs-video
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - build: true
          default: true
          locale: en
          name: English
          nav:
            - Home: index.md
            - SMP:
              - Permissions: smp/permissions.md
              - config.yml: smp/config.yml.md
              - Admin:
                - mutedPlayers.yml: smp/admin/mutedPlayers.yml.md
              - Discord:
                - config.yml: smp/discord/config.yml.md
                - save.yml: smp/discord/save.yml.md
              - Fusions:
                - fusionName.yml: smp/fusions/fusionName.yml.md
              - Language:
                - en.yml: smp/language/en.yml.md
              - MultiMine:
                - config.yml: smp/multiMine/config.yml.md
              - Server:
                - config.yml: smp/server/config.yml.md
              - Status:
                - config.yml: smp/status/config.yml.md
                - save.yml: smp/status/save.yml.md
              - Waypoints:
                - config.yml: smp/waypoints/config.yml.md
                - save.yml: smp/waypoints/save.yml.md
            - MultiMine:
              - config.yml: mm/config.yml.md
              - MultiMine:
                - config.yml: mm/multiMine/config.yml.md
              - Language:
                - en.yml: mm/language/en.yml.md
            - Color Codes: colorcode.md
        - build: true
          default: false
          locale: de
          name: Deutsch
          nav:
            - Home: index.md
            - SMP:
              - Berechtigungen: smp/permissions.md
              - config.yml: smp/config.yml.md
              - Admin:
                - mutedPlayers.yml: smp/admin/mutedPlayers.yml.md
              - Discord:
                - config.yml: smp/discord/config.yml.md
                - save.yml: smp/discord/save.yml.md
              - Fusions:
                - fusionName.yml: smp/fusions/fusionName.yml.md
              - Language:
                - de.yml: smp/language/de.yml.md
              - MultiMine:
                - config.yml: smp/multiMine/config.yml.md
              - Server:
                - config.yml: smp/server/config.yml.md
              - Status:
                - config.yml: smp/status/config.yml.md
                - save.yml: smp/status/save.yml.md
              - Waypoints:
                - config.yml: smp/waypoints/config.yml.md
                - save.yml: smp/waypoints/save.yml.md
            - MultiMine:
              - config.yml: mm/config.yml.md
              - MultiMine:
                - config.yml: mm/multiMine/config.yml.md
              - Language:
                - en.yml: mm/language/de.yml.md
            - Color Codes: colorcode.md

markdown_extensions:
  - mdx_truly_sane_lists
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details


